base: 'https://www.psacontrols.com/'
baseVariants:
  -
    base: 'https://psacontrols.codebomb-websolutions.de'
    condition: 'applicationContext == "Development/Testing"'
  -
    base: 'https://psacontrols.ddev.site'
    condition: 'applicationContext == "Development/Ddev"'
disableStaticFileCache: false
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE.utf8
    navigationTitle: Deutsch
    flag: de
    hreflang: de-DE
    websiteTitle: ''
  -
    title: English
    enabled: true
    locale: en_US.utf8
    hreflang: en-US
    base: /en/
    websiteTitle: ''
    navigationTitle: English
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
rootPageId: 1
websiteTitle: ''
