####
# Example of what CKEditor can all bring
###

# Load default processing options
imports:
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Processing.yaml' }
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml' }
    - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml' }

# Add configuration for the editor
# For complete documentation see https://ckeditor.com/docs/ckeditor5/latest/features/index.html
editor:
    config:
        contentsCss: "EXT:cbw_sitepackage/Resources/Public/css/Backend/rte.css"
        style:
            definitions:
                # block level styles
                - { name: 'Dunkelblauer Hintergrund', element: 'p', classes: ['background-dark-blue', 'bodytext'],  }
                - { name: 'Hellblauer Hintergrund', element: 'p', classes: ['background-bright-blue', 'bodytext'],  }
                - { name: 'Primärer Button', element: 'a', classes: ['btn', 'btn-primary'],  }
                - { name: 'Sekundärer Button', element: 'a', classes: ['btn', 'btn-secondary'],  }
                # Inline styles
                - { name: 'Orange Marker', element: 'span', classes: ['marker-orange'], styles: { color: 'orange' } }

        heading:
            options:
                - { model: 'paragraph', title: 'Paragraph' }
                - { model: 'heading2', view: 'h2', title: 'Heading 2' }
                - { model: 'heading3', view: 'h3', title: 'Heading 3' }
                - { model: 'formatted', view: 'pre', title: 'Pre-Formatted Text' }

        toolbar:
            items:
                - clipboard
                - removeFormat
                - undo
                - redo
                # grouping separator
                - '|'
                - find
                - selectAll
                - '|'
                - link
                - insertTable
                - tableColumn
                - tableRow
                - mergeTableCells
                - '|'
                - sourceEditing
                - showBlocks
                - horizontalLine
                # line break
                - '-'
                - bold
                - italic
                - underline
                - strikethrough
                - subscript
                - superscript
                - softhyphen
                - '|'
                - bulletedList
                - numberedList
                - blockQuote
                - indent
                - outdent
                - alignment
                - '|'
                - specialCharacters
                - '-'
                - style
                - heading

        alignment:
            options:
                - { name: 'left', className: 'text-start' }
                - { name: 'center', className: 'text-center' }
                - { name: 'right', className: 'text-end' }
                - { name: 'justify', className: 'text-justify' }
